"""Meeting lifecycle state machine and flag catalogue."""
from enum import Enum
from typing import Dict, Set


class MeetingState(str, Enum):
    DRAFT = "DRAFT"
    SCHEDULED = "SCHEDULED"
    INVITATION_SENT = "INVITATION_SENT"
    WAITING_FOR_LEAD = "WAITING_FOR_LEAD"
    LEAD_JOINED = "LEAD_JOINED"
    SALES_PERSON_JOINED = "SALES_PERSON_JOINED"
    IN_PROGRESS = "IN_PROGRESS"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    RECORDING_PROCESSING = "RECORDING_PROCESSING"
    TRANSCRIPT_PROCESSING = "TRANSCRIPT_PROCESSING"
    AI_ANALYSIS_PROCESSING = "AI_ANALYSIS_PROCESSING"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    CLOSED = "CLOSED"
    NO_SHOW = "NO_SHOW"
    FAILED = "FAILED"


S = MeetingState

# Ordered position used by the UI journey and to reject backwards moves.
STATE_ORDER = [
    S.DRAFT,
    S.SCHEDULED,
    S.INVITATION_SENT,
    S.WAITING_FOR_LEAD,
    S.LEAD_JOINED,
    S.SALES_PERSON_JOINED,
    S.IN_PROGRESS,
    S.MEETING_COMPLETED,
    S.RECORDING_PROCESSING,
    S.TRANSCRIPT_PROCESSING,
    S.AI_ANALYSIS_PROCESSING,
    S.ANALYSIS_COMPLETED,
    S.FOLLOW_UP_REQUIRED,
    S.CLOSED,
]

_PROCESSING = {S.RECORDING_PROCESSING, S.TRANSCRIPT_PROCESSING, S.AI_ANALYSIS_PROCESSING}

TRANSITIONS: Dict[MeetingState, Set[MeetingState]] = {
    S.DRAFT: {S.SCHEDULED, S.FAILED},
    S.SCHEDULED: {S.INVITATION_SENT, S.WAITING_FOR_LEAD, S.LEAD_JOINED, S.IN_PROGRESS, S.MEETING_COMPLETED, S.NO_SHOW, S.FAILED},
    S.INVITATION_SENT: {S.WAITING_FOR_LEAD, S.LEAD_JOINED, S.SALES_PERSON_JOINED, S.IN_PROGRESS, S.MEETING_COMPLETED, S.NO_SHOW, S.FAILED},
    S.WAITING_FOR_LEAD: {S.LEAD_JOINED, S.SALES_PERSON_JOINED, S.IN_PROGRESS, S.MEETING_COMPLETED, S.NO_SHOW, S.FAILED},
    S.LEAD_JOINED: {S.SALES_PERSON_JOINED, S.IN_PROGRESS, S.MEETING_COMPLETED, S.FAILED},
    S.SALES_PERSON_JOINED: {S.LEAD_JOINED, S.IN_PROGRESS, S.MEETING_COMPLETED, S.FAILED},
    S.IN_PROGRESS: {S.MEETING_COMPLETED, S.FAILED},
    S.MEETING_COMPLETED: _PROCESSING | {S.ANALYSIS_COMPLETED, S.FOLLOW_UP_REQUIRED, S.CLOSED, S.FAILED},
    S.RECORDING_PROCESSING: {S.TRANSCRIPT_PROCESSING, S.AI_ANALYSIS_PROCESSING, S.FAILED, S.MEETING_COMPLETED},
    S.TRANSCRIPT_PROCESSING: {S.AI_ANALYSIS_PROCESSING, S.FAILED, S.MEETING_COMPLETED},
    S.AI_ANALYSIS_PROCESSING: {S.ANALYSIS_COMPLETED, S.FOLLOW_UP_REQUIRED, S.FAILED},
    S.ANALYSIS_COMPLETED: {S.FOLLOW_UP_REQUIRED, S.CLOSED, S.AI_ANALYSIS_PROCESSING},
    S.FOLLOW_UP_REQUIRED: {S.CLOSED, S.ANALYSIS_COMPLETED, S.AI_ANALYSIS_PROCESSING},
    S.CLOSED: {S.AI_ANALYSIS_PROCESSING, S.FOLLOW_UP_REQUIRED},
    S.NO_SHOW: {S.CLOSED, S.MEETING_COMPLETED},
    # A failed processing stage can be retried from the admin monitor.
    S.FAILED: _PROCESSING | {S.MEETING_COMPLETED, S.CLOSED},
}


def can_transition(current: str, target: str) -> bool:
    if current == target:
        return True
    try:
        return MeetingState(target) in TRANSITIONS.get(MeetingState(current), set())
    except ValueError:
        return False


# States in which the frontend should keep polling.
ACTIVE_PROCESSING_STATES = {s.value for s in _PROCESSING} | {S.MEETING_COMPLETED.value}

# Friendly labels used by the UI and exports.
STATE_LABELS = {
    S.DRAFT: "Draft",
    S.SCHEDULED: "Scheduled",
    S.INVITATION_SENT: "Invitation Sent",
    S.WAITING_FOR_LEAD: "Waiting for Lead",
    S.LEAD_JOINED: "Lead Joined",
    S.SALES_PERSON_JOINED: "Sales Person Joined",
    S.IN_PROGRESS: "In Progress",
    S.MEETING_COMPLETED: "Completed",
    S.RECORDING_PROCESSING: "Recording Processing",
    S.TRANSCRIPT_PROCESSING: "Transcript Processing",
    S.AI_ANALYSIS_PROCESSING: "Analysis Processing",
    S.ANALYSIS_COMPLETED: "Analysis Complete",
    S.FOLLOW_UP_REQUIRED: "Follow-up Required",
    S.CLOSED: "Closed",
    S.NO_SHOW: "No Show",
    S.FAILED: "Failed",
}


class Flag(str, Enum):
    # Meeting
    MEETING_SCHEDULED = "MEETING_SCHEDULED"
    INVITATION_SENT = "INVITATION_SENT"
    EMAIL_SENT = "EMAIL_SENT"
    EMAIL_FAILED = "EMAIL_FAILED"
    LEAD_JOINED = "LEAD_JOINED"
    SALES_PERSON_JOINED = "SALES_PERSON_JOINED"
    MEETING_STARTED = "MEETING_STARTED"
    MEETING_COMPLETED = "MEETING_COMPLETED"
    MEETING_DATA_PENDING = "MEETING_DATA_PENDING"
    NO_SHOW = "NO_SHOW"
    RECORDING_AVAILABLE = "RECORDING_AVAILABLE"
    RECORDING_MISSING = "RECORDING_MISSING"
    TRANSCRIPT_AVAILABLE = "TRANSCRIPT_AVAILABLE"
    ANALYSIS_PENDING = "ANALYSIS_PENDING"
    ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
    # Sales
    PITCH_COMPLETED = "PITCH_COMPLETED"
    PITCH_INCOMPLETE = "PITCH_INCOMPLETE"
    PRICING_DISCUSSED = "PRICING_DISCUSSED"
    PRICING_NOT_DISCUSSED = "PRICING_NOT_DISCUSSED"
    OBJECTION_RAISED = "OBJECTION_RAISED"
    NO_OBJECTION_DETECTED = "NO_OBJECTION_DETECTED"
    FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
    FOLLOW_UP_NOT_REQUIRED = "FOLLOW_UP_NOT_REQUIRED"
    # Lead
    HIGH_INTEREST_SIGNAL = "HIGH_INTEREST_SIGNAL"
    LOW_INTEREST_SIGNAL = "LOW_INTEREST_SIGNAL"
    PURCHASE_INTENT_SIGNAL = "PURCHASE_INTENT_SIGNAL"
    PRICE_CONCERN = "PRICE_CONCERN"
    TIME_CONCERN = "TIME_CONCERN"
    DECISION_PENDING = "DECISION_PENDING"
    REQUESTED_MORE_INFORMATION = "REQUESTED_MORE_INFORMATION"
    # Technical
    RECORDING_PROCESSING = "RECORDING_PROCESSING"
    TRANSCRIPT_PROCESSING = "TRANSCRIPT_PROCESSING"
    AI_ANALYSIS_PROCESSING = "AI_ANALYSIS_PROCESSING"
    RECORDING_FAILED = "RECORDING_FAILED"
    TRANSCRIPT_FAILED = "TRANSCRIPT_FAILED"
    AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED"
    WEBHOOK_RECEIVED = "WEBHOOK_RECEIVED"
    WEBHOOK_PROCESSING_FAILED = "WEBHOOK_PROCESSING_FAILED"
    ATTENDANCE_SYNC_FAILED = "ATTENDANCE_SYNC_FAILED"


FLAG_CATEGORY = {
    **{f: "meeting" for f in [
        Flag.MEETING_SCHEDULED, Flag.INVITATION_SENT, Flag.EMAIL_SENT, Flag.EMAIL_FAILED,
        Flag.LEAD_JOINED, Flag.SALES_PERSON_JOINED,
        Flag.MEETING_STARTED, Flag.MEETING_COMPLETED, Flag.MEETING_DATA_PENDING, Flag.NO_SHOW,
        Flag.RECORDING_AVAILABLE, Flag.RECORDING_MISSING, Flag.TRANSCRIPT_AVAILABLE,
        Flag.ANALYSIS_PENDING, Flag.ANALYSIS_COMPLETE]},
    **{f: "sales" for f in [
        Flag.PITCH_COMPLETED, Flag.PITCH_INCOMPLETE, Flag.PRICING_DISCUSSED, Flag.PRICING_NOT_DISCUSSED,
        Flag.OBJECTION_RAISED, Flag.NO_OBJECTION_DETECTED, Flag.FOLLOW_UP_REQUIRED, Flag.FOLLOW_UP_NOT_REQUIRED]},
    **{f: "lead" for f in [
        Flag.HIGH_INTEREST_SIGNAL, Flag.LOW_INTEREST_SIGNAL, Flag.PURCHASE_INTENT_SIGNAL, Flag.PRICE_CONCERN,
        Flag.TIME_CONCERN, Flag.DECISION_PENDING, Flag.REQUESTED_MORE_INFORMATION]},
    **{f: "technical" for f in [
        Flag.RECORDING_PROCESSING, Flag.TRANSCRIPT_PROCESSING, Flag.AI_ANALYSIS_PROCESSING,
        Flag.RECORDING_FAILED, Flag.TRANSCRIPT_FAILED, Flag.AI_ANALYSIS_FAILED,
        Flag.WEBHOOK_RECEIVED, Flag.WEBHOOK_PROCESSING_FAILED, Flag.ATTENDANCE_SYNC_FAILED]},
}

# Flags derived from AI output (the UI marks these "AI generated").
AI_DERIVED_FLAGS = {
    f.value for f in [
        Flag.PITCH_COMPLETED, Flag.PITCH_INCOMPLETE, Flag.PRICING_DISCUSSED, Flag.PRICING_NOT_DISCUSSED,
        Flag.OBJECTION_RAISED, Flag.NO_OBJECTION_DETECTED, Flag.FOLLOW_UP_REQUIRED, Flag.FOLLOW_UP_NOT_REQUIRED,
        Flag.HIGH_INTEREST_SIGNAL, Flag.LOW_INTEREST_SIGNAL, Flag.PURCHASE_INTENT_SIGNAL, Flag.PRICE_CONCERN,
        Flag.TIME_CONCERN, Flag.DECISION_PENDING, Flag.REQUESTED_MORE_INFORMATION,
    ]
}
